version: 2.1

orbs:
  ruby: circleci/ruby@1.4.0
  aws-ecr: circleci/aws-ecr@7.2.0

jobs:
  build:
    docker:
      - image: 'cimg/ruby:3.0.3'
    steps:
      - checkout
      - ruby/install-deps
  build_and_push:
    docker:
      - image: cimg/base:2022.02
    steps:
      - setup_remote_docker:
          version: 20.10.11
      - aws-ecr/build-and-push-image:
          repo: rails-kata
          extra-build-args: |
            --build-arg SECRET_KEY_BASE=$SECRET_KEY_BASE \
            --build-arg DATABASE_URL=$DATABASE_URL \
workflows:
  build_deploy:
    jobs:
      - build
      - build_and_push:
          requires:
            - build
          filters:
            branches:
              only: main
